### ISSUE TITLE
AzNamingTool - Update resourceType config using api call gives error

### ISSUE THREAD

**Issue by ciprianglg** [microsoft/CloudAdoptionFramework#106]
When you update the resource type config file using post method from the api /api/ResourceTypes/PostConfig it give you some validation errors:

{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-4db0bd302c23a01a53c7a4730fadb151-9cf0687d72cf2130-00",
    "errors": {
        "[300].ShortName": [
            "The ShortName field is required."
        ],
        "[304].ShortName": [
            "The ShortName field is required."
        ],
        "[305].ShortName": [
            "The ShortName field is required."
        ],
        "[306].ShortName": [
            "The ShortName field is required."
        ],
        "[307].ShortName": [
            "The ShortName field is required."
        ],
        "[308].ShortName": [
            "The ShortName field is required."
        ]
    }
}

When you update the same json config file through the webinterface, error is not given back:

![image](https://user-images.githubusercontent.com/48557485/197982676-a28193bc-8c19-47a5-8254-8b80cb6a5dfc.png)

![image](https://user-images.githubusercontent.com/48557485/197982707-06ab196b-4518-4348-94fa-7fc9c5f5f197.png)

Even if the errors are present using api post method, configuration is updated.

**Comment by BryanSoltis** [comment]
Hi @ciprianglg,

Thank you for your feedback. In looking at the code, I can see the error you are experiencing. 


**Short Answer**
The "Import" function of the Configuration page for resource types will work. The API will theow an error because it is attempting to validate the JSON contains "valid" resource types. Currently, the "Short Name" value is required, so the API is complaining when it does its initial validation. We will update this in a future release to not require the short name value. 


**Long Answer**
It's related to the "short name" value being required for resource types. Originally, the tool required this value, as we used it for a number of cross reference purposes throughout the tool. Recently, we have updated several aspects to allow empty short names, however, the Models/resourcetype.cs class still has the **Required** attribute on the **ShortName** property. 

While the Configuration and API both utilize the same functionality to import the items, the API is automatically validating the JSON to ensure the items are valid. Because the **ShortName** is required, the API is stopping all processing because of the empty values. This is just how .NET processes the input. 

The Configuration page allows the import, because it does not automatically validate the JSON (it does once the code actually attempts to process it), so it allows it be updated. 

In the next update, we'll change it so the ShortName field is not required. This should resolve the API issue. (FYI, we have a large update scheduled to go live in the next few days. This change will be in a future update).

Thank you again for your feedback!

-Bryan

**Comment by ciprianglg** [comment]
@BryanSoltis thanks for update. Also as you mentioned, the same behavior is in the latest version. Waiting for the future ones then:), but i consider that ShortName should be there, and try to fix the Configuration page to do the validation.
Idea is that without the short name, you can't generate a name, so i consider it mandatory somehow:).

**Comment by BryanSoltis** [comment]
Hi @ciprianglg,
THere is a PR waiting to be merged that will allow the short name value to be blank. Some resource types are a "low level" scop, meaning someone would never generate a name for them.

Example:
![image](https://user-images.githubusercontent.com/13591910/199009456-6fbeee8f-b72a-4570-9ec7-a3d6a58715b8.png)

I have updated the ResourceType.cs model to not require the ShortName value. This should resolve the issue you are seeing when importing via the API.

=Bryan

**Comment by ciprianglg** [comment]
@BryanSoltis Indeed, in the version 2.3.1 you will not get error back if you update a resource without a short name, using api call. I will close this as fixed.
