### ISSUE TITLE
Exclusion of component not working

### ISSUE THREAD

**Issue by iamjatingohil** [microsoft/CloudAdoptionFramework#95]
Under windows VM resource type i have excluded some components like Environment, location, Project. But when i try to generate name it throws an error that such components are required.

Error Message: You must supply the required components. ResourceProjAppSvc value was not provided. ResourceInstance value was not provided.

**Comment by iamjatingohil** [comment]
![image](https://user-images.githubusercontent.com/114494654/192538253-62447ce8-cb89-4ab4-94a8-e8a128205e64.png)
![image](https://user-images.githubusercontent.com/114494654/192538341-7bcca4f4-bb5d-46a0-947a-5ed7c2568709.png)

**Comment by BryanSoltis** [comment]
Hi @iamjatingohil,

Thank you for your feedback. The issue you are seeing is most likely due to multiple resource types having the same "short name" value. In your case, both the "Compute/virtualMachines - Windows" and "Compute/virtualMachines - Linux" resource types both have "vm" as the short name. The Generate page cannot distinguish between the two and is picking the "Linux" version and applying its "Optional/Excluded" configuration to the name generation.

We are aware of the problem and already have a fix ready to deploy. We will be publishing a new version of the tool in the next couple of weeks that will resolve this. In the meantime, you could do one of the following to get around the problem:

- Set the "Compute/virutalMachines - Linux" type configuration to match the "Windows" one in your site. If the Generate page "thinks" it's the Linux version, it will still allow the name generation. (RECOMMENDED)

or 

- In you Configuration page, update the short name for the "Linux" or "Windows" resource types to unique values (NOT RECOMMENDED, unless you have already modified other resource type short name values) 

In the end, our fix will resolve this issue. Thank you again for your feedback!

- Bryan

**Comment by BryanSoltis** [comment]
To clarify, our upcoming fix WILL allow for duplicate names with resource types. Hope this helps!

- Bryan
